apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: mg-as-sh
  namespace: demo
spec:
  databaseRef:
    name: mg-sh
  compute:
    shard:
      trigger: "On"
      podLifeTimeThreshold: 1m
      minAllowed:
        memory: 250Mi
      maxAllowed:
        memory: 8Gi
      controlledResources: ["memory"]
      containerControlledValues: "RequestsAndLimits"
      resourceDiffPercentage: 10