apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: mg-as-rs
  namespace: demo
spec:
  databaseRef:
    name: mg-rs
  compute:
    replicaSet:
      trigger: "On"
      podLifeTimeThreshold: 3m
      minAllowed:
        cpu: 540m
        memory: 256Mi
      maxAllowed:
        cpu: 1
        memory: 1Gi
      controlledResources: ["cpu"]
      inMemoryStorage:
        usageThresholdPercentage: 70
        scalingFactorPercentage: 50
