apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-sh
  namespace: demo
spec:
  version: "percona-4.4.10"
  storageEngine: inMemory
  shardTopology:
    configServer:
      replicas: 3
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
    mongos:
      replicas: 2
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
    shard:
      configSecret:
        name: inmemory-config
      replicas: 3
      shards: 2
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "700m"
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "2Gi"
  storageType: Ephemeral
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        args:
          - --compatible-mode
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  terminationPolicy: WipeOut

# kubectl create secret generic -n demo inmemory-config --from-file=./inmemory-config