apiVersion: ops.kubedb.com/v1alpha1
kind: MySQLOpsRequest
metadata:
  name: update-my
  namespace: demo
spec:
  type: UpdateVersion
  databaseRef:
    name: group
  updateVersion:
    targetVersion: 8.0.32
  apply: IfReady

