apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  name: esv
  namespace: demo
spec:
  type: VerticalScaling
  apply: Always
  databaseRef:
    name: es-combined
  verticalScaling:
    node:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi