apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: restart
  namespace: demo
spec:
  type: Restart
  databaseRef:
    name: mg-rs
  readinessCriteria:
    oplogMaxLagSeconds: 30
    objectsCountDiffPercentage: 10
  timeout: 10m
  apply: Always