apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: vertical
  namespace: demo
spec:
  databaseRef:
    name: mg-rs
  type: VerticalScaling
  verticalScaling:
    replicaSet:
      limits:
        cpu: 4800m
        memory: 2516582Ki
      requests:
        cpu: 600m
        memory: 600Mi