apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: mops-mg-rs-only
  namespace: demo
spec:
  databaseRef:
    name: mg-rs
  type: VerticalScaling
  verticalScaling:
    replicaSet:
      limits:
        cpu: 4800m
        memory: 3682930Ki
      requests:
        cpu: 600m
        memory: 899153Ki
