apiVersion: kubedb.com/v1alpha2
kind: ProxySQL
metadata:
  name: my-proxy
  namespace: demo
spec:
  version: "2.3.2-debian"
  replicas: 1
  mode: GroupReplication
  backend:
    name: my-group
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 42004
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  syncUsers: true
