apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: upgrade
  namespace: demo
spec:
  type: Upgrade
  databaseRef:
    name: mg-rs
  upgrade:
    targetVersion: 5.0.2
  apply: IfReady
