# apiVersion: kubedb.com/v1alpha2
# kind: MongoDB
# metadata:
#   name: mongo
#   namespace: demo
# spec:
#   version: "4.2.3"
#   replicaSet:
#     name: "replicaset"
#   podTemplate:
#     spec:
#       resources:
#         requests:
#           cpu: "200m"
#           memory: "200Mi"
#   replicas: 3
#   # storageEngine: inMemory
#   storageType: Durable
#   storage:
#     storageClassName: "standard"
#     accessModes:
#       - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi
#   hidden:
#     podTemplate:
#       spec:
#         resources:
#           requests:
#             cpu: "200m"
#             memory: "200Mi"
#     replicas: 2
#     storage:
#       storageClassName: "standard"
#       accessModes:
#         - ReadWriteOnce
#       resources:
#         requests:
#           storage: 400Mi
#   terminationPolicy: WipeOut

---
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mongo
  namespace: demo
spec:
  version: "4.2.3"
  shardTopology:
    configServer:
      replicas: 3
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "200m"
              memory: "2000Mi"
      storage:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 400Mi
    mongos:
      replicas: 2
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "200m"
              memory: "2000Mi"
    shard:
      replicas: 3
      shards: 2
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "300m"
              memory: "3000Mi"
      storage:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  hidden:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
    replicas: 2
    storage:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 400Mi
  terminationPolicy: WipeOut