apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-rs
  namespace: demo
spec:
  version: "percona-4.4.10"
  replicas: 3
  replicaSet:
    name: "rs1"
  podTemplate:
    spec:
#      volumes:
#        - name: hello
#          secret:
#            secretName: test-secret
#      volumeMounts:
#        - name: hello
#          mountPath: /data/configdb-db
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "4"
#          memory: "2Gi"
#  configSecret:
#    name: inmemory-config
  storageEngine: inMemory
  storageType: Ephemeral
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509
#  monitor:
#    agent: prometheus.io/operator
#    prometheus:
#      exporter:
#        args:
#          - --compatible-mode
#      serviceMonitor:
#        labels:
#          release: prometheus
#        interval: 10s
  terminationPolicy: WipeOut

# The name has to be mongod.conf
# kubectl create secret generic -n demo inmemory-config --from-file=./others/mongod.conf