apiVersion: ops.kubedb.com/v1alpha1
kind: RedisOpsRequest
metadata:
  name: expansion
  namespace: demo
spec:
  databaseRef:
    name: rdc
  type: VolumeExpansion
  volumeExpansion:
    mode: Online
    redis: 12Gi
