apiVersion: autoscaling.kubedb.com/v1alpha1
kind: RedisSentinelAutoscaler
metadata:
  name: rda
  namespace: demo
spec:
  databaseRef:
    name: sentinel
  opsRequestOptions:
    apply: IfReady
    timeout: 5m
  compute:
    sentinel: 
      trigger: "On"
      podLifeTimeThreshold: 5m
      minAllowed:
        cpu: 600m
        memory: 600Mi
      maxAllowed:
        cpu: 1
        memory: 1Gi
      controlledResources: ["cpu", "memory"]
  # storage:
  #   sentinel:
  #     trigger: "On"
  #     usageThreshold: 60
  #     scalingThreshold: 50