apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pg-upgrade
  namespace: demo
spec:
  type: Upgrade
  upgrade:
    targetVersion: "14.2"
  databaseRef:
    name: demo-pg
